version: '3.7'

################################################################################
# NETWORKING CONFIGURATION
################################################################################

networks:

    traefik:
        external:
            name: traefik_reverse-proxy

################################################################################
# SERVICES CONFIGURATION
################################################################################

services:

    ####################################
    # HOSTED JUPYTER NOTEBOOK
    ####################################

    jupyter:
        container_name: jupyter
        image:          juftin/jupyter:latest
        networks:
            traefik: null
        restart:        unless-stopped
        user:           root
        environment:
            NB_USER:       ${ADMIN_USER}
            NB_UID:        ${PUID}
            NB_GID:        ${PGID}
            JUPYTER_TOKEN: ${ADMIN_PASSWORD}
            PYTHONPATH:    $${PYTHONPATH}:/home/${ADMIN_USER}/${SHARED_DIRECTORY_NAME}
        volumes:
            - ${SHARED_DIRECTORY}:/home/${ADMIN_USER}/${SHARED_DIRECTORY_NAME}:rw
        labels:
            traefik.enable:                                             true
            traefik.http.routers.jupyter-rtr.rule:                      Host(`${JUPYTER_SUBDOMAIN}.${DOMAIN_NAME}`)
            traefik.http.routers.jupyter-rtr.service:                   jupyter-svc
            traefik.http.services.jupyter-svc.loadbalancer.server.port: 8888
            # SET ENTRYPOINTS TO "HTTP" AND MIDDLEWARES TO "chain-local-testing@file" WHEN RUNNING LOCALLY
            traefik.http.routers.jupyter-rtr.entrypoints:               http
            traefik.http.routers.jupyter-rtr.middlewares:               chain-local-testing@file